spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: sa
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
liquibase:
  change-log: db.changelog-master.xml